version: "3.5"

services:
  mongo-server2:
    image: mongoentnew
    container_name: appsdb2
    hostname: appsdb2
    volumes: 
      - ./init-replica.sh:/home/init-replica.sh
    ports:
      - 27018:27017 
    environment:
      DEPLOYMENT: script

  mongo-server3:
    image: mongoentnew
    container_name: appsdb3
    hostname: appsdb3
    ports:
      - 27019:27017    
    environment:
      DEPLOYMENT: replicaset

  mongo-server4:
    image: mongoentnew
    container_name: appsdb4
    hostname: appsdb4
    ports:
      - 27020:27017
    environment:
      DEPLOYMENT: replicaset